# air.toml

# Root of your project
root = "."
# Directory to watch for changes
watch_dir = "." # Directory to watch

#Temporary directory where air will store temporary files
temp_dir = "/tmp"


# Application settings
[app]

# Environment (development, production)
environment = "development"

# Application name
name = "Go React Chat App"

# Application version
version = "0.0.1"

# Log level (info, warn, error, debug)
log_level = "info"

# Path to the main package to run
main = "go_react_chat_app"

# Binary output directory
bin = "bin"

# File extensions to watch
extensions = ["go"]

# Files to exclude
exclude = ["temp/*", "client/*"]

# Run the binary with the following flags
# (uncomment to add any)
# run_flags = ""

# Ignore files or directories
ignore = ["vendor", "tmp", ".git"]

# Delay in seconds before restarting
# (uncomment to set a delay)
# delay = 0

# Reload settings
# (uncomment to enable)
# reload = true
